# Generated by Django 4.0.5 on 2022-07-02 09:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import investors.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username')),
                ('email', models.EmailField(error_messages={'unique': 'Investor with this email address already exists'}, max_length=255, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Investor phone number', max_length=50, null=True, verbose_name='Phone Number')),
                ('password', models.CharField(help_text='Investor password', max_length=128, validators=[django.core.validators.MinLengthValidator(limit_value=8), django.core.validators.RegexValidator(inverse_match=True, message='Password cannot contain spaces', regex='\\s')], verbose_name='Password')),
                ('is_verified', models.BooleanField(default=False, help_text='Investor email address is verified', verbose_name='Is Verified')),
                ('kyc_front_view', models.ImageField(blank=True, help_text='KYC front view', null=True, upload_to=investors.models.save_image_investors, verbose_name='KYC Front View')),
                ('kyc_back_view', models.ImageField(blank=True, help_text='KYC back view', null=True, upload_to=investors.models.save_image_investors, verbose_name='KYC Back View')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('other_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Name')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True, verbose_name='Gender')),
                ('mugshot', models.ImageField(blank=True, null=True, upload_to=investors.models.save_image_investors, verbose_name='Mugshot')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal/ZIP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorWithdrawal',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='Database ID', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('method', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('PayPal', 'PayPal'), ('Bank', 'Bank')], default='Bitcoin', max_length=50, verbose_name='Method')),
                ('address', models.CharField(blank=True, help_text='Wallet address', max_length=255, null=True, verbose_name='Address')),
                ('email', models.CharField(blank=True, help_text='PayPal email address', max_length=255, null=True, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, help_text='Name of recieving bank', max_length=255, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=255, null=True, verbose_name='Account Number')),
                ('swift_code', models.CharField(blank=True, help_text='Bank Swift Code', max_length=255, null=True, verbose_name='Swift Code')),
                ('amount', models.CharField(blank=True, help_text='Amount to withdraw', max_length=50, null=True, verbose_name='Amount')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Investor')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorInvestment',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='Database ID', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Starter plan', 'Starter plan'), ('Advance plan', 'Advance plan'), ('Premium plan', 'Premium plan'), ('Sublime plan', 'Sublime plan'), ('Luxury plan', 'Luxury plan')], default='Starter plan', max_length=255, verbose_name='Plan')),
                ('amount', models.CharField(blank=True, help_text='Amount invested in this plan', max_length=50, null=True, verbose_name='Amount')),
                ('days', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Days')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending')], default='Pending', help_text='Status of this investment', max_length=10, verbose_name='Status')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Investor')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertTraders',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('mugshot', models.ImageField(blank=True, null=True, upload_to=investors.models.save_image_experts, verbose_name='Mugshot')),
                ('full_name', models.CharField(help_text='Trader full name', max_length=255, verbose_name='Full Name')),
                ('win_rate', models.CharField(blank=True, default='90%', max_length=50, null=True, verbose_name='Win Rate')),
                ('profit_share', models.CharField(blank=True, default='20%', max_length=50, null=True, verbose_name='Profit Share')),
                ('investors', models.ManyToManyField(blank=True, help_text='Investors linked with this trader', to=settings.AUTH_USER_MODEL, verbose_name='Investors')),
            ],
        ),
    ]
