# Generated by Django 4.0.5 on 2022-06-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_investorwithdrawal_investorinvestment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorinvestment',
            name='plan',
            field=models.CharField(choices=[('Starter plan', 'Starter plan'), ('Advance plan', 'Advance plan'), ('Premium', 'Premium'), ('Sublime plan', 'Sublime plan'), ('Luxury plan', 'Luxury plan')], default='Starter plan', max_length=255, verbose_name='Plan'),
        ),
    ]
