# Generated by Django 4.0.5 on 2022-06-28 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorWithdrawal',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='Database ID', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('method', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('PayPal', 'PayPal'), ('Bank', 'Bank')], default='Bitcoin', max_length=50, verbose_name='Method')),
                ('address', models.CharField(blank=True, help_text='Wallet address', max_length=255, null=True, verbose_name='Address')),
                ('email', models.CharField(blank=True, help_text='PayPal email address', max_length=255, null=True, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, help_text='Name of recieving bank', max_length=255, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=255, null=True, verbose_name='Account Number')),
                ('swift_code', models.CharField(blank=True, help_text='Bank Swift Code', max_length=255, null=True, verbose_name='Swift Code')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Investor')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorInvestment',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='Database ID', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Starter plan', 'Starter plan'), ('Advance plan', 'Advance plan'), ('Starter basic advance plan', 'Starter basic advance plan'), ('Sublime plan', 'Sublime plan'), ('Luxury plan', 'Luxury plan')], default='Starter plan', max_length=255, verbose_name='Plan')),
                ('amount', models.CharField(blank=True, help_text='Amount invested in this plan', max_length=50, null=True, verbose_name='Amount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('status', models.BooleanField(choices=[('Active', 'Active'), ('Pending', 'Pending')], default='Pending', help_text='Status of this investment', verbose_name='Status')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Investor')),
            ],
        ),
    ]
