# Generated by Django 4.0.5 on 2022-06-28 11:06

from django.db import migrations, models
import investors.models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_investorwithdrawal_investorinvestment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_back_view',
            field=models.ImageField(blank=True, help_text='KYC back view', null=True, upload_to=investors.models.save_image, verbose_name='KYC Back View'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_front_view',
            field=models.ImageField(blank=True, help_text='KYC front view', null=True, upload_to=investors.models.save_image, verbose_name='KYC Front View'),
        ),
    ]
