# Generated by Django 4.0.5 on 2022-06-28 11:09

from django.db import migrations, models
import investors.models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_alter_user_kyc_back_view_alter_user_kyc_front_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mugshot',
            field=models.ImageField(blank=True, null=True, upload_to=investors.models.save_image, verbose_name='Mugshot'),
        ),
    ]
