# Generated by Django 4.0.5 on 2022-07-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_alter_investorinvestment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorinvestment',
            name='days',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Days'),
        ),
    ]
