# Generated by Django 4.0.5 on 2022-07-02 12:33

from django.db import migrations, models
import investors.models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_alter_user_mugshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mugshot',
            field=models.ImageField(blank=True, upload_to=investors.models.save_image_investors, verbose_name='Mugshot'),
        ),
    ]
