# Generated by Django 4.0.5 on 2022-07-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_investorinvestment_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorinvestment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='investorwithdrawal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
