# Generated by Django 4.0.5 on 2022-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_alter_user_mugshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorinvestment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending')], default='Pending', help_text='Status of this investment', max_length=10, verbose_name='Status'),
        ),
    ]
