# Generated by Django 4.0.5 on 2022-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_alter_investorinvestment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorwithdrawal',
            name='amount',
            field=models.CharField(blank=True, help_text='Amount to withdraw', max_length=50, null=True, verbose_name='Amount'),
        ),
    ]
