# Generated by Django 4.0.5 on 2022-07-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_alter_experttraders_options_user_current_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investment_plan',
            field=models.CharField(blank=True, default='....', help_text='Investors investment plan', max_length=255, verbose_name='Investment Plan'),
        ),
    ]
