# Generated by Django 4.0.5 on 2022-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0007_user_investment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest_rate',
            field=models.CharField(blank=True, default='0.00', help_text='Interest rate for the current investment plan', max_length=50, verbose_name='Interest Rate'),
        ),
    ]
