FROM python:3.11-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# install system dependencies
RUN apt update && apt-get -y install netcat

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ./entrypoint.dev.sh .
RUN chmod +x entrypoint.dev.sh

COPY . .

ENTRYPOINT [ "sh", "/app/entrypoint.dev.sh" ]
