# This action deploys my containerized apps. Uses docker-compose up to start app
# some times, docker-compose up (step 4) just keeps loading for some minutes
# then stops with an error, implying that the server is not responding

name: CD Deploy (VPS)

on:
  workflow_dispatch:


jobs:

  create-env-file:

    runs-on: self-hosted

    steps:
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}

          envkey_DB_ENGINE: ${{ secrets.DB_ENGINE }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

          envkey_CSRF_COOKIE_DOMAIN: ${{ secrets.CSRF_COOKIE_DOMAIN }}
          envkey_CSRF_COOKIE_SAMESITE: ${{ secrets.CSRF_COOKIE_SAMESITE }}
          envkey_CSRF_COOKIE_HTTPONLY: ${{ secrets.CSRF_COOKIE_HTTPONLY }}
          envkey_CSRF_COOKIE_SECURE: ${{ secrets.CSRF_COOKIE_SECURE }}
          envkey_CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
          envkey_SESSION_COOKIE_SAMESITE: ${{ secrets.SESSION_COOKIE_SAMESITE }}
          envkey_SESSION_COOKIE_HTTPONLY: ${{ secrets.SESSION_COOKIE_HTTPONLY }}
          envkey_SESSION_COOKIE_SECURE: ${{ secrets.SESSION_COOKIE_SECURE }}
          envkey_SECURE_HSTS_SECONDS: ${{ secrets.SECURE_HSTS_SECONDS }}
          envkey_SECURE_HSTS_PRELOAD: ${{ secrets.SECURE_HSTS_PRELOAD }}
          envkey_SECURE_SSL_REDIRECT: ${{ secrets.SECURE_SSL_REDIRECT }}
          envkey_SECURE_HSTS_INCLUDE_SUBDOMAINS: ${{ secrets.SECURE_HSTS_INCLUDE_SUBDOMAINS }}

          envkey_CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}

          envkey_EMAIL_BACKEND: ${{ secrets.EMAIL_BACKEND }}
          envkey_EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          envkey_EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

          envkey_VIRTUAL_HOST: ${{ secrets.VIRTUAL_HOST }}
          envkey_LETSENCRYPT_HOST: ${{ secrets.LETSENCRYPT_HOST }}

          envkey_ACME_CA_URI: ${{ secrets.ACME_CA_URI }}
          envkey_DEFAULT_EMAIL: ${{ secrets.DEFAULT_EMAIL }}
          envkey_NGINX_PROXY_CONTAINER: ${{ secrets.NGINX_PROXY_CONTAINER }}
          envkey_NGINX_DOCKER_GEN_CONTAINER: ${{ secrets.NGINX_DOCKER_GEN_CONTAINER }}


  # deploy-app:

  #   runs-on: self-hosted

  #   steps:
  #     - name: Checkout codebase
  #       uses: actions/checkout@v3

  #     - name: Ping Hostinger :)
  #       run:  ping -c4 hostinger.com

  #     - name: Show docker containers
  #       run:  docker ps -a

  #     - name: Run docker compose up
  #       run:  docker compose -f docker-compose.yml up --detach --build